name: Expo CI/CD

on:
  push:
    branches:
      - front

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.7.0'
          cache: 'npm'
          # Aponta para o local correto do package-lock.json na subpasta
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        # Garante que o npm install rode dentro do diretório front
        run: npm install
        working-directory: front

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build with EAS
        # Garante que o build do EAS também seja disparado de dentro da pasta front
        run: eas build --platform android --non-interactive --profile preview
        working-directory: front
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
