name: Expo CI/CD

on:
  push:
    branches:
      - front

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.7.0'
          cache: 'npm' # Ativa o cache nativo do GitHub Actions para o npm

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        # Instalamos via npm para evitar o erro de 'exit code 1' do yarn que ocorreu anteriormente
        run: npm install -g eas-cli

      - name: Build with EAS
        # Este comando envia o build para a nuvem da Expo, economizando recursos do Actions
        run: eas build --platform android --non-interactive --profile preview
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
